### ISSUE TITLE
block is inserted with empty run/lumi lists

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#45]
see https://github.com/dmwm/CRABServer/issues/7279
the block https://github.com/dmwm/CRABServer/files/8804693/block.json.gz  (in gzipped json) is passed
as argument to `insertBulkBlock(blockDump)` API and the resulting dataset is found in `prod/phys03` instance with the correct file and file parent list. But the run and lumi list for the inserted file are empty.

The information about run and lumi is present in the blockDump, so I think this is a problem on DBS end.

If you try to insert this in your DB, you will need to migrate there the parent dataset 
`/GenericTTbar/HC-CMSSW_7_0_4_START70_V7-v1/GEN-SIM-RECO` from `prod/global`

**Comment by vkuznet** [comment]
@belforte , thanks for reporting this problem. Indeed, I was able to reproduce it. From the DBS server logs I found that queries into filelumis were failing with the following error:
```
INSERT ALL
INTO ORA$PTT_TEMP_FILE_LUMIS_1653996226762394
...
[2022-05-31 11:23:46.889648618 +0000 UTC m=+508252.049151524] filelumis.go:361: Unable to insert FileLumis records, error ORA-00942: table or view does not exist
```

The problem is the following:
- the new server uses concurrent inserts into file_lumis table if number of run-lumis entries is more than a chunk size (currently set to 500). Therefore, we seems to not see this issue with blocks where run-lumis are smaller then a chunk size
- when number of run-lumis entries more than chunk size I used two methods
   - one is to use temporary table (which seems to me we are having issue with creation permission on production database and I need to resolve this separately with Kate)
   - or, we can insert using chunks. But for this query I identified different issue and fixed it in the following commits:
     - https://github.com/dmwm/dbs2go/commit/8ed44c0feb173ce23848e523da7dae98812bc2d4
     - https://github.com/dmwm/dbs2go/commit/7851c571835719f48f019bf776fea472b1728257

I deployed new version of DBSWriter into cmsweb testbed and I strongly encourage you to test your workflows with blocks where there are lots of lumis, we need more than 500 per file to trigger concurrent insert. In my local tests I used dummy data and was able to successfully insert it. But I need extra validation from other workflows to verify the injection and then I can put new version of DBSWriter into production.

**Comment by belforte** [comment]
well... you mentioned you would have liked more testing with possibly diverse workflows before putting in production, but if that one block is good enough, so be it and less work for us. If anything, it will be easier to test if it is in production.

**Comment by vkuznet** [comment]
One block is enough from independent workflow. New version in production now.
