### ISSUE TITLE
concerned about DBS Migrate server design

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#68]
I have opened a set of issues lately, but in the end they were all "minor technicalities", some bugs, some work on clarifying new migration server semantic and nailing down details of communication with new DBS servers. Let me do something different now.

In here I'd rather like to suggest a change in DBS Migrate server design. Up to you to listen and in case discuss further or agree or reject or whatever. This does not affect mechanics of CRAB/DBS interactions, it is only a worry of mine about possible problems.

I know it is your server and your code and in the end you will do whatever you see better. But I felt I have to voice
my concern at least once. I understand that we are late in the development cycle, maybe too late to entertain design changes, but I was not aware of how things work internally in new DBS code until now.

AFAIU current design is:
 1. client submit request to migrate block B from some input DBS instance (typ. prod/global)
 2. DBSMigrate looks up this block in prod/global and also locates all its ancestors
 3. DBSMigrate creates migration requests for this blocks and all ancestors in proper cronological order and stores them in the DB
 4. then DBSMigrate returns to client the full list of all migration requests that it creates
 
I see a problem there, because some blocks (imagine MINIAOD or NANOAOD) have hundreds of ancestors (I have seen one
migration request create in excess of 600 block migration requests).Therefore creating all of them takes time and exposes to the risk that an error occurs at some point in the process leaving the requests in an undefined state.
I have been looking at DBSMigrate server log with `tail -f` while I was submitting migration requests and I think I have seen cases where it just stops at some point w/o reaching the usual termination.

I understand that this may be rare, may happen more now because I am using testbed which may have less crunching capability,
etc. etc. and that in the end this may be a matter of taste, since worst that can happen is that migration request is ends in error and it will be retried (hopefully with delay and exponential backoff) at which point some ancestor blocks my have been migrated already.

But ....
1. I do not like to get errors
2. I do not like to receive that list of 600+ migration requests since I only care if my block eventually makes it (yes, Valentin gave me a way to check status of only that block, but.. what am I supposed to do with the list then ? dump it in my log in case it is needed for debug ?
3. I do not like that in case of problems debugging of DBSMigrate/DBSMigration interaction[*] requires CRAB logs
  [*](DBSMigration is another server which reads the list of migration requests from the DB and actually performs them, in proper order and porting all parentage realtionships to new DBS instance). 
 4. I worry that even if everything works, the connection from my Client to DBSMigrate needs to stay up during the full time that all the above happens, risking to trigger cmsweb FrontEnd timeouts (like e.g. the HTTP 502 in https://github.com/dmwm/dbs2go/issues/64)
 5. In any case my client is exposed to a lot of what are actually internal details of how migrations are done inside DBS, which it should instead be protected from. To imagine an extreme situation, DBS developerss should be free to completely change the algorithm in the current design, w/o clients like CRAB being aware.

I would rather propose that the design here follows the same line (IIUC) as old python-based DBS:
 1. DBSMigrate is very simple and robust, and simply records the request to migrate one block in its DB and immediately assigns it a unique number which client can use to track it
 2. later on DBS Migration server can do all the complicated work to derive parentage and migrate ancestor blocks in proper order etc.etc. and can keep track as it likes using a new DB table or creating more migrationIds or whatever.
 3. In this way client is fully isolated, and clinet/server transaction are quick, simple and with maximum chance of success.
 4. debugging of problems if any is fully inside DBS domain, no access to client logs needed, only a migration request ID to point to the problem
 5. it goes w/o saying that this different design has worked extremely well for many years. Of course new implementation with a different language offers a chance to simplify and change things and new code will be extremely robust and well debugged etc. etc., I am not putting that into question. We all know difference between design and implementation.

end of preaching/ranting/hot-air-puffing.... do whatever you want with this

**Comment by vkuznet** [comment]
Stefano, thank you for your feedback. I always strive to get better experience with users.

The DBS migration process (not migration of dataset but rather entire system) is very tedious since many things are different. I'll not point to them but only to the process. As such, I followed very closely the DBS Python server architecture and only modernize it to newer technology. Said that let me first answer to your "But ..." questions
1. I agree that no one wants to get errors, but when things go south we need to know what happens. Many things in Python codebase were unclear, hidden, etc. I tried to standarize them and make all issues visible because, see next item
2. all processing should be logged, moreover, the verbose log allows to identify and debug issues. I would strongly suggest to keep log of requests and dump output of submit API. This will allow to debug the issue and idenfity what is wrong. As you keep CRAB server log, as I keep DBS, WMArchive, Monitoring, apache, k8s logs the DBS migration server output is not that different. And, if you (will) keep CRAB Publisher logs it is very good.
3. the crab initiate the requests and therefore it is ultimate source of the initial request. When you experience problem with DAS client, I always ask what is your query. Here is the same, I need to know your query in order to start debugging. Building scalable, concurrent system is not an easy task and asking client (in this case CRAB) to provide what it was doing is starting point of any debug process
4. this request is debatable, but certainly any request should be accepted within minimal interval of time. Until I investigate  #64 I can't say much and will not speculate
5. current design does not force anything from CRAB client, i.e. you call `/submit` API and feel free to close the connection. There is not requirement to keep it alive, there is no requirement to get back the results since client knows the migration input and therefore can check its status at any time using `/status` API.

Said that, I'll evaluate your design feedback to see how it fits. But w/o saying the Python server had so many issues that even client have not seen them on its side, we always struggled with them on server side, large RAM footprint, inability to port code to k8s, no horizontal scalability, etc. As such finding a compromise is a big challenge and we almost done it. I truly appreciate your commitment to validate the process but moving DBS from one implementation to another is significant effort and getting things working w/o errors taking time. We made it for DBSReader and DBSWriter, and significantly improved them, ported to k8s, etc., and I'm sure will reach stability of migration server soon.

**Comment by belforte** [comment]
thanks Valentin, I do not see need to further debate. Things are surely clear to you.

Yes, we keep Publisher logs as well, and wherever possible preferred the 'ignore the error and try again in 30 min'. Of course I need to watch for things not getting better after retries and that can be tricky, but we'll need to switch at some point, adapt monitoring to new conditions and again learn as we go. I have inherited this Publisher from others (Diego Ciangottini) and have been trying to adapt as needed w/o totally disrupting it, even if great logging was not Diego's strong point. My problem is that I do not have an easy way to retry block insert, but migrations already use the the submit-now-and-check-later which you advice,  simply a matter to make it clear when it is time to report a problem.

As you well know our problem is to deal with rare exceptions. Everything we run usually works well, we have a successful Computing system at the end of the day and CMS processes its data timely, but we process a lot of stuff and things which happens 1/10^6 become a visible operational disturbance :-( 

Anyhow, we'll make it.

**Comment by vkuznet** [comment]
Stefano, I had a look at architecture of new server and walk through your suggested list. The main difference between new implementation and old one is that in new server parents of requested migration input are resolved in DBSMigrate server rather in DBSMigration one. This has two implication:
- obviously due to extra work on a client side we have larger time to wait for output from '/submit' API. And, it shows multiple migration requests instead of one. This is what you observe.
- but on server side it reduce RAM/CPU requirements on DBSMigration server which now only pick up migration blocks from migration table and transfer the data from one DBS to another. As such it can scale better.

I'll evaluate both approaches and make a decision but only after I will get resolution of my request for schema changes from DBA. What I plan to do is to benchmark how much time it takes to resolve parents within migration submission request and make a decision if I need to move this part into DBSMigration server. Apart from that, the work flow  and architecture among Go and Py are very similar (both servers share the same DB schema). I'll post my findings in this ticket and will follow closely your guidelines.

**Comment by belforte** [comment]
Yes. I think that's all I meant. There's some work to do, you need to decide if to make client wait while you do or not.
As a client, of course, I prefer not to wait. But for you that means an extra step in migration server.
You clearly understand pros and cons here.

**Comment by vkuznet** [comment]
Stefano, in order to do proper benchmarking of time required to find out all parents of a specific input I need to find out a dataset or block which may have large number of parents. If I recall correctly you mentioned before that you saw output from submit API which had hundreds of entries (I think you mentioned 600). Do you know by any chance a dataset or block which may have large number of parents, or at least give me some pointers to which pattern of datasets I should look at. This will help me to perform stress tests to decide about proper design architecture of the server.

**Comment by belforte** [comment]
Sure, I will look for it. But let's not worry too much here. First priority is to get it to work and deploy in production. Optimizations like this are transparent to users and can be done at any time once we have good understanding and some more experience.

**Comment by belforte** [comment]
here we go:
dataset='/ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/RunIISummer19UL18NanoAODv2-106X_upgrade2018_realistic_v15_L1v1-v1/NANOAODSIM'

I submitted migration request for the full dataset, 537 migrationIds in "seconds" !!
``` python
dataset='/ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/RunIISummer19UL18NanoAODv2-106X_upgrade2018_realistic_v15_L1v1-v1/NANOAODSIM'
data = {'migration_url': globUrl, 'migration_input': dataset}
print(data)
print(migrateApi.url)

result = migrateApi.submitMigration(data)
print(len(result))
```
gave
```
dataset='/ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/RunIISummer19UL18NanoAODv2-106X_upgrade2018_realistic_v15_L1v1-v1/NANOAODSIM'
data = {'migration_url': globUrl, 'migration_input': dataset}
print(data)
print(migrateApi.url)

result = migrateApi.submitMigration(data)
print(len(result))
```

[sorry I use Jupyter notebook for this test and have not found a way to properly copy/paste]

**Comment by belforte** [comment]
here's a dataset with data (not MC), 309 blocks migrations, I counted elapsed seconds:
```
{'migration_url': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', 'migration_input': '/EGamma/Run2018D-UL2018_MiniAODv2_NanoAODv9-v3/NANOAOD'}
https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate
309
elapsed secs: 2.6593685150146484
```

**Comment by vkuznet** [comment]
Stefano, thanks for finding this large datasets. If I read your posting correctly you are submitting for migration to cmsweb-testbed int/phys03 which means it is Go based server, am I right or wrong? If so, it means that current server implementation does not add additional overhead when look-up parents (which is what I expect).

**Comment by belforte** [comment]
Yes, you read correctly, this is go-base server. Yes "when it works it flies" :-)   BTW, you can very likely pick any NANO* dataset and get same amount of parents, i got those in the list of what CRAB users are using currently in ES, but others should also do.

**Comment by vkuznet** [comment]
@belforte , after your report with https://github.com/dmwm/dbs2go/issues/72 and https://github.com/dmwm/dbs2go/issues/69 I made necessary changes to DBS Migrate server to switch its behavior similar to Python server. Your concerns outlined here and filed issued convinced me to made a switch. The change was applied in this commit 134af018b35190a8eda4e77bf8f23bbf23d3724e and I tagged new version as v00.06.17

What is changed and how it will affect you (clients):
- originally, I processed client's request directly to find out its parents and return all migration requests back to the client. As you correctly observed this lead to some latency. Until number of parents is relatively small it is not an issue. But with larger number of parents, e.g. on a scale of O(1K) it becomes an issue since we may hit FE threshold. Since I do not know if large number of parents is going to be common use-case it leads me to conclude that we should support async behavior of DBSMigrate server.
- to do that, I added new code called `QUEUED` (with new id 5) which is what is returned back to the client with its request. It means the following:
  - the request is accepted and its parentage info is started in background (using goroutines, in Python server it was done through threads), i.e. it is not blocking operation. This is why only **ONE** entry will be returned.
  - once parentage information is obtained, the request is moved to `PENDING` status. It means that it is ready to picked up by DBSMIgration server for processing.
  - the rest behavior is identical with sync server, i.e. the DBSMigration server will pick up `PENDING` requests and process them (i.e. migrate blocks) in their correspoding order

This redesign will allow to avoid long requests which may lead to FE timeouts, but at the same time will preserve existing functionality. As such I don't expect you need to change anything in CRAB client code. The returned JSON is still a list of requests, but this time it will contain only one request dict (the original migration input). This will restore behavior of python server too where your client will not be blocked and will only see one migration request output.

I'm building new code and once it is ready I'll updated testbed with it. Then I'll ask you to submit usual amount of duplicate migration requests that we'll verify its functionality. Please note, I only made changes to change behavior of DBSMigrate server from sync to async mode. As such I do not foresee any changes in migration logic. But of course we will need a fresh test of new version.

**Comment by vkuznet** [comment]
BTW, I setup context timeout of new async server to 600sec. It means that this is maximum amount of time the new DBSMigrate server will use to find parents. This is configurable parameter though. Based on your example in https://github.com/dmwm/dbs2go/issues/69 I estimate that for O(7K) parents we need 300 seconds. I consider this as extreme outlier and therefore decided to use 600sec as default value for async server. It also means that after this time interval the DBSMigrate will cancel this async request to find parents (and free resources). This will allow to perform parent retrieval in background without blocking original client's request and at the same time avoid FE timeouts.

**Comment by vkuznet** [comment]
And, the new DBSMigrate async server now is deployed on cmsweb testbed. Please resume testing and report back with your findings.

**Comment by belforte** [comment]
Thanks Valentin. I am always amazed by how fast you are.
Parasitic migration to testbed is continuously running since a week, let's see how it goes. if I find problems I will open new issues.

Did you give any thought to the fact that building a separate ancestors tree for each block to be migrated will result in a very large number of duplicates and it may be much more expedient to identify the (few) ancestor datasets and simply migrate them fully w/o bothering to know which blocks are exactly needed ?

**Comment by vkuznet** [comment]
Building separate migration trees (requests) will be very challenging task since it will require knowledge of order between independent trees. So far I doubt it is possible and worth to do until we get production ready DBS migration servers. Since I made a change to async server I think we will be in a good shape but I'll put separate thoughts on how to parallelize things in a future since new architecture allows such parallelization.

**Comment by belforte** [comment]
hmm... I am not sure we are talking about same thing here and do not want to push you into more work, especially by mistake. I am looking for simplifications. Maybe I simply fail at it.

**Comment by vkuznet** [comment]
closing as resolved before migration to k8s.
