### ISSUE TITLE
HTTP 502 submitting migration request to testbed

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#72]
this does not look fatal, repeated retry seems to work, but it is annoying
could it be due to server overload and tied to discussion in #68 ?

I will add more as I gather more statistics

```
2022-07-29 11:30:33,063:ERROR: Request to migrate /WplusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM#a5196c89-c7cc-48b1-8fc7-d5b1d310ad26 failed.
Request detail: {'migration_url': 'https://cmsweb-prod.cern.ch:8443/dbs/prod/global/DBSReader', 'migration_input': '/WplusJetsToMuNu_H2ErratumFix_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM#a5196c89-c7cc-48b1-8fc7-d5b1d310ad26'}
DBS3 exception: HTTP Error 502: 
URL=https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate/submit
Code=502
Message=Proxy Error
Header=HTTP/1.1 502 Proxy Error
Date: Fri, 29 Jul 2022 09:25:32 GMT
Server: Apache
Content-Length: 472
Content-Type: text/html; charset=iso-8859-1


Body=<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/auth/complete/dbs/int/phys03/DBSMigrate/submit">POST&nbsp;/auth/complete/dbs/int/phys03/DBSMigrate/submit</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>

```

**Comment by vkuznet** [comment]
The proxy error clearly an issue with FE talking to BE. This happens when BE was not reached for whatever reason, e.g. BE server was down or cannot process HTTP request. Since the issue was filed 18 days ago I doubt I can reliably investigate it today, but I'll keep eye on migration server. One possibility is that the pod where DBS migration server was restarted, another (as you pointed out) that server was overloaded. I plan to enable horizontal scaling during this week and will test it. This should eliminate possibility of overloading. Let's keep this issue open and put new entry if it occurs again.

**Comment by vkuznet** [comment]
This error seems to come from restart of DBSMigrate servers. Here is what I see on k8s testbed cluster:
```
dbs2go-phys03-m-684d687cc8-7gwf2           2/2     Running     65 (146m ago)   8d
dbs2go-phys03-m-684d687cc8-dtp7n           2/2     Running     77 (143m ago)   8d
dbs2go-phys03-m-684d687cc8-rvxp2           2/2     Running     59 (147m ago)   8d
```
and, the actual restart happens due to to this error in DBSMigrate server:
```
[2022-08-16 07:24:38.577296676 +0000 UTC m=+132103.365603856] utils.go:104: ERROR DBSError Code:127 Description:Invalid HT
TP request Function:dbs.utils.tlsCerts Message:failed to parse X509 proxy Error: crypto/tls: failed to parse key: asn1: syntax error: data truncated
```
So, I think we should adjust proxy management which will fix the restart, which by itself cause upcoming request to fail from FE to BE when restart happen. This explain the behavior you observed.

**Comment by vkuznet** [comment]
Please see this explanation to address this issue: https://github.com/dmwm/dbs2go/issues/68#issuecomment-1218168500

**Comment by vkuznet** [comment]
closing as resolved before migration to k8s.
