### ISSUE TITLE
stuck migrations

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#77]
this migration (and similar ones) is in status 5 since 11 hours.
 date -d @1661422464
Thu 25 Aug 12:14:24 CEST 2022
while now
date
Thu 25 Aug 23:06:43 CEST 2022

Such a long time is unexpected and worrysome.
is this an effect of the troubles in #76 ? Or a different problem ?

```
[{'create_by': '/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch',
  'creation_date': 1661422464,
  'last_modification_date': 1661422464,
  'last_modified_by': '/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch',
  'migration_input': '/BsToJPsiPhi_JPsiToMuMu_PhiToKK_EtaPtFilter_SoftQCDnonD_TuneCP5_13TeV-pythia8-evtgen/RunIISummer20UL16RECO-106X_mcRun2_asymptotic_v13-v1/AODSIM#dcf59d81-b0a8-439e-b273-15e910c2ec4c',
  'migration_request_id': 3326981,
  'migration_server': None,
  'migration_status': 5,
  'migration_url': 'https://cmsweb-prod.cern.ch:8443/dbs/prod/global/DBSReader',
  'retry_count': 0}]
```
another example is e.g. `'migration_request_id': 3326951` for another block of same dataset
```
[{'create_by': '/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch',
  'creation_date': 1661420971,
  'last_modification_date': 1661420971,
  'last_modified_by': '/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch',
  'migration_input': '/BsToJPsiPhi_JPsiToMuMu_PhiToKK_EtaPtFilter_SoftQCDnonD_TuneCP5_13TeV-pythia8-evtgen/RunIISummer20UL16RECO-106X_mcRun2_asymptotic_v13-v1/AODSIM#88723e53-db1b-44e3-b78d-d55c9d1b8caa',
  'migration_request_id': 3326951,
  'migration_server': None,
  'migration_status': 5,
  'migration_url': 'https://cmsweb-prod.cern.ch:8443/dbs/prod/global/DBSReader',
  'retry_count': 0}]

```

**Comment by vkuznet** [comment]
Stefano, it is certainly effect of #76 since clean-up procedure seems to block everything. Since it is late in US and at CERN Is very late I suggest the following:
- let's decide on set of actions. We can two things:
- either rollback everything to python server. If so, I suggest that you reply here and send email to @muhammadimranfarooqi to roll it over tomorrow. I'm fine with that, or
- we need to clean-up DB with old migration requests. This may take time as I discovered the query I used takes very long time to clean-up things. I can remove clean-up part of the migration server, but it will require coding and making new release. In any way I can only start working on this tomorrow. Please reply here and send email to @muhammadimranfarooqi  if we need to rollback.

**Comment by vkuznet** [comment]
@belforte , @mapellidario I identified 9 stale migration requests in DB, see below. I think there are side effect of issue with clean-up and since they are in QUEUED state I suggest to simply remove them and you can restart them on your side. I provided their migration request IDs, timestamp and input. Since now `/remove` API is working you may simply run curl command to remove them, or if you prefer you can reply in this ticket and I can remove them manually in DB:
```
SQL> select migration_request_id, creation_date, migration_input FROM cms_dbs3_prod_phys03_owner.MIGRATION_REQUESTS WHERE migration_status=5 order by creation_date asc;
             3326931    1661417390
/EphemeralZeroBias13/Run2022C-v1/RAW#4405b012-11f1-44cb-aac4-1f3eb13a2ebd

             3326933    1661417489
/EphemeralZeroBias15/Run2022C-v1/RAW#e4a81462-3057-42c3-8a42-6fc8d14f4e53

             3326948    1661419772
/EphemeralZeroBias17/Run2022C-v1/RAW#f6cef4e5-0dc2-4bfd-b804-72ce23b61713

             3326951    1661420971
/BsToJPsiPhi_JPsiToMuMu_PhiToKK_EtaPtFilter_SoftQCDnonD_TuneCP5_13TeV-pythia8-evtgen/RunIISummer20UL16RECO-106X_mcRun2_asymptotic_v13-v1/AODSIM#88723e53-db1b-44e3-b78d-d55c9d1b8caa

             3326955    1661421271
/EphemeralZeroBias3/Run2022C-v1/RAW#f9250e4c-9679-4486-960e-ca92568e9b1a

             3326962    1661421473
/EphemeralZeroBias4/Run2022C-v1/RAW#a82e423b-384b-497e-aa17-7b55576cd5c7

             3326966    1661421554
/EphemeralZeroBias11/Run2022C-v1/RAW#f521b71f-c7bd-4019-821a-2533570e6278

             3326968    1661421571
/EphemeralZeroBias19/Run2022C-v1/RAW#89511e42-1c0e-4195-acf3-e3605f8d9654

             3326981    1661422464
/BsToJPsiPhi_JPsiToMuMu_PhiToKK_EtaPtFilter_SoftQCDnonD_TuneCP5_13TeV-pythia8-evtgen/RunIISummer20UL16RECO-106X_mcRun2_asymptotic_v13-v1/AODSIM#dcf59d81-b0a8-439e-b273-15e910c2ec4c
```

**Comment by belforte** [comment]
please remove them, CRAB Publisher will automatically create new ones as needed.
I have no brain left today,

**Comment by vkuznet** [comment]
done

**Comment by belforte** [comment]
can be closed
