### ISSUE TITLE
migration in status 5 since ~12h

### ISSUE THREAD

**Issue by mapellidario** [dmwm/dbs2go#83]
### brief description

The files from task `220918_180601:nbinnorj_crab_JMENanoRun3_v2p1_EGamma_Run2022D-PromptReco-v1` are failing to be published by CRAB Publisher because they require the mirgation `3401574`,  which is still in status 5 despite being submitted around 12 hours ago.

It is possible that I am simply too greedy, but from my (very little) user experience with DBSMigration so far I had the impression that the status change `5->0` is usually quite quick and I worry that something may be wrong.

What should we do? Is it worth investigating what happened or should we simply try and remove and submit the migration again if it stays in status 5 for too long?

Thanks you very much for you help and kudos for the great work, this is the first "issue" with DBSMigration we see since weeks, which is a good thing!

### some further information

The migration `3401574` seems to be the only one stuck in status 5 at the moment:

```plaintext
> curl -L --key $X509_USER_PROXY --cert $X509_USER_PROXY "https://cmsweb-prod.cern.ch/dbs/prod/phys03/DBSMigrate/status?migration_status=5"
[
{"create_by":"/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch","creation_date":1663534952,"last_modification_date":1663534952,"last_modified_by":"/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch","migration_input":"/EGamma/Run2022D-PromptReco-v1/MINIAOD#9b00d04b-4691-48d3-83b3-477fd9617c22","migration_request_id":3401574,"migration_server":null,"migration_status":5,"migration_url":"https://cmsweb-prod.cern.ch:8443/dbs/prod/global/DBSReader","retry_count":0}
]
```

Something strange may have happened, since DBSMigrate server says that the migration was moved to status 0

```plaintext
> hostname && pwd
vocms0750.cern.ch
/cephfs/product/dbs-logs
> grep "3401574" dbs2go-*-m-*-20220918
[...]
dbs2go-phys03-m-6494c59fd6-n7zfh.log-20220918:[2022-09-18 21:02:32.65678911 +0000 UTC m=+551201.391874504] migrate.go:1378: update migration request 3401574 to status 0
[...]
```

**Comment by vkuznet** [comment]
Dario, the logs reveal the following message:
```
[2022-09-18 21:32:53.093813555 +0000 UTC m=+553021.828898949] handlers.go:474: DBSPostHandler: API=submit, dn=[/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch], uri=/dbs/prod/phys03/DBSMigrate/submit
[2022-09-18 21:32:53.094131219 +0000 UTC m=+553021.829216613] handlers.go:514: API=submit params=map[] createBy=/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch separator=','
[2022-09-18 21:32:53.094331789 +0000 UTC m=+553021.829417182] migrate.go:669: submit migration request  {"migration_url":
"https://cmsweb-prod.cern.ch:8443/dbs/prod/global/DBSReader", "migration_input": "/EGamma/Run2022D-PromptReco-v1/MINIAOD#9
b00d04b-4691-48d3-83b3-477fd9617c22"}
...
[2022-09-18 21:32:53.345052223 +0000 UTC m=+553022.080137616] handlers.go:86: DBSError Code:125 Description:DBS Migration error Function:dbs.migrate.SubmitMigration Message:Migration request /EGamma/Run2022D-PromptReco-v1/MINIAOD#9b00d04b-4691-48d3-83b3-477fd9617c22, id=0 Error: migration request /EGamma/Run2022D-PromptReco-v1/MINIAOD#9b00d04b-4691-48d3-83b3-477fd9617c22 is already exist in DB with id=3401574
```
It means that crab client called `SubmitMigration` API when this migration request was already there. Once I start walking backwards in log file I found the following:

```
[2022-09-18 21:02:32.658228471 +0000 UTC m=+551201.393313854] migrate.go:866: Migration request for /EGamma/Run2022D-Promp
tReco-v1/MINIAOD#ca04d20c-837d-429a-b10e-ad2dff52218a insert MigrationRequest record {MIGRATION_REQUEST_ID:0 MIGRATION_URL
:https://cmsweb-prod.cern.ch:8443/dbs/prod/global/DBSReader MIGRATION_INPUT:/EGamma/Run2022D-PromptReco-v1/MINIAOD#ca04d20
c-837d-429a-b10e-ad2dff52218a MIGRATION_STATUS:0 MIGRATION_SERVER: CREATE_BY:/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch CREATION_DATE:1663534952 LAST_MODIFIED_BY:/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch LAST_MODIFICATION_DATE:1663534952 RETRY_COUNT:0}
[2022-09-18 21:02:32.658463442 +0000 UTC m=+551201.393548824] migrate.go:1330: unable to query statement:
SELECT MIGRATION_SERVER
FROM cms_dbs3_prod_phys03_owner.MIGRATION_REQUESTS
WHERE MIGRATION_REQUEST_ID = :migration_request_id

error=ORA-02396: exceeded maximum idle time, please connect again

[2022-09-18 21:02:32.65870935 +0000 UTC m=+551201.393794744] migrate.go:746: finished {MIGRATION_REQUEST_ID:3401574 MIGRATION_URL:https://cmsweb-prod.cern.ch:8443/dbs/prod/global/DBSReader MIGRATION_INPUT:/EGamma/Run2022D-PromptReco-v1/MINIAOD#
9b00d04b-4691-48d3-83b3-477fd9617c22 MIGRATION_STATUS:5 MIGRATION_SERVER: CREATE_BY:/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch CREATION_DATE:1663534952 LAST_MODIFIED_BY:/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch LAST
_MODIFICATION_DATE:1663534952 RETRY_COUNT:0} with 4 migration requests
```

So, I see the following data flow:
- at 2022-09-18 21:02:32.658228471 we got submit request API call
- at 2022-09-18 21:02:32.658463442 we got ORA-02396 query error which fails due to idle timeout ORACLE connection

I think we got unlucky since during that time one of the ORACLE connection timeout due to idle state. This cause the request to stay in QUEUD state.

Therefore, we have two solutions (which I suggest you evaluate an decide how to use in a future):
- you can either delete request and submit it again
- or, you can explicitly process the request via `/process` API, in this case you will do:
```
# migration document
cat > m.json << EOF
{
    "migration_rqst_id":65023
}
EOF

# submit migration request to explicitly process it
curl -H "Content-Type: application/json" -d@$PWD/m.json \
    http://localhost:9898/dbs2go-migrate/process
```

I think it would be interested to know if you'll use second method for two reason:
- I think we never used this API before and it is good chance to see how it will work
- it does not contradict the first approach to delete and resubmit, but you may decide in your workflow that you may try explicitly process migration requests which stale for too long. And, if such procedure does not work after couple of times you may declare failure and open a ticket.

But I think both approaches are the same in your side. Now, at least we know the reason of failure and it is ORACLE connection issue rather a failure in a business logic of DBSMigrate/DBSMigration. I need to study and see what to do with such ORACLE failures though and I think we should keep this ticket open until I find solution. My bet that I should check ORACLE failure if make exception for this kind of error and retry obtain ORACLE connection again.

**Comment by belforte** [comment]
Thanks for diagnosis Valentin. IMHO it should be DBS migration server duty to check on failures and do proper restarts. Things may always fail for various reasons, Oracle restarts, CMSWEB restarts, networks issues, all unplanned and unexpected. But from client side (i.e. us) once we have submitted a request and logged an ID for it, it is fair to assume that the remote server will keep doing its best to fulfill it, or mark as failed.
We do retry failed migrations, but if server does not announce a "failure", it means to us that server is still working on it, so best approach is not to touch it.

I do not like to code things like "if status=5 for N hours, than read it as status=9". It fully destroys the agreed-upon semantics of what status means.

The /process API is intriguing. Indeed we never use it and never looked at it. I am not sure how we should deal with it though, exactly for the above reason. Is this a "forced retry ?" . By the way, you stil have a retry counter and a being retried status in your migration API. Is this not a marvelous use case for "the server tries again" ?

**Comment by belforte** [comment]
@vkuznet let me try now to move from high level "is this my or your responsibility" to the details of what happens, which of course I may have misunderstood here. Maybe you can simply look at what exactly are the requirements for a migration to move from 5 to 0 and verify whether some checks could be introduced to make it go to  3 in a case like this ?
IIUC migrations in status 3 will be automatically retried ( up to 3 times )  as per https://github.com/dmwm/dbs2go/blob/master/docs/MigrationServer.md

If not because of unexpected, transient glitches like this, what are the conditions which may cause a migration to go in status 3 ?

Also, IIUC, when client submits  a migration ID is created with status=5 in an ad-hoc table, and the migration /submit API only returns success if this happened. After that there is a polling cycle and migration is acted upon and moved to 0. So it appeats that the code which should move it to 0 is continuosly called in at each polling cycle, and continuously failing. That's really something to deal with inside server.

Finally, I believe that /process should also be something that server may use, not client. IIUC the documetnation it is an API which forcefully pushes something into action while the server is full time busy processing its own queue... ahem... if there are free resources, the server should use them. If there are now, better that client does not mess with an overloaded system. I do not see an use case for CRAB to try to force migration server hand this way. We patiently retry to request migration for needed blocks and only stop when those are found in target DBS. The semantic I was given in DBS3 times was "try to submit and DBS will tell you if migration is already in progress" so requesting a migration which is already there is sort of part of the contract. But if the new server prefers a "check for a migration in progress before submitting", we can certainly add it. That means 2 calls instead of 1 in large majority of cases, but server is fast enough that it could handle w/o sweat. Your call.

**Comment by vkuznet** [comment]
Stefano, I understand everything you're saying and I'm working on solution. The only issue is how to test this unforeseen ORACLE errors. I'll put something in production server today/tomorrow and it would be useful if we'll not touch this request 3401574 as I'll use it to test the solution.

**Comment by vkuznet** [comment]
I deployed new code which now handles such stale requests and voila without my or yours intervention it works. Your request is processed and migrated with status 2 (SUCCESS).
```
scurl -s "https://cmsweb-prod.cern.ch/dbs/prod/phys03/DBSMigrate/status?migration_request_id=3401574" | jq
[
  {
    "create_by": "/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch",
    "creation_date": 1663534952,
    "last_modification_date": 1663534952,
    "last_modified_by": "/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch",
    "migration_input": "/EGamma/Run2022D-PromptReco-v1/MINIAOD#9b00d04b-4691-48d3-83b3-477fd9617c22",
    "migration_request_id": 3401574,
    "migration_server": "dbs2go-phys03-migration-6f75c685c9-bvg7h",
    "migration_status": 2,
    "migration_url": "https://cmsweb-prod.cern.ch:8443/dbs/prod/global/DBSReader",
    "retry_count": 0
  }
]
```
Please confirm from your end and let me know if we can close the issue, or close it on your own if you're happy with resolution.

**Comment by mapellidario** [comment]
Shortly after your last comment, CRAB Publisher managed to properly publish all the files. Everything looks good to me. Thank you very much Valentin for the very prompt implementation of a solution. I will happily close this issue :)

![image](https://user-images.githubusercontent.com/16376695/191499626-f3de0073-039f-4acf-add7-c0316c7e4db2.png)

(image taken from https://monit-grafana.cern.ch/goto/Cvccyx7Vk?orgId=11)
