### ISSUE TITLE
Blocks failing to be inserted with Error: concurrency error

### ISSUE THREAD

**Issue by amaltaro** [dmwm/dbs2go#98]
Hello,
I found 2 central production blocks that are failing to be inserted into DBS since June, they are:
```
 /DYJetsToMuMu_M-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Winter23Reco-TRKRealistic_AlcaRecoRealisticTRK_REAL_126X_mcRun3_2022_realistic_postEE_v2-v2/GEN-SIM-RECO#c44686c3-86fa-4fc3-9902-ae328914b317
/DYJetsToMuMu_M-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Winter23Digi-TRKRealistic_REAL_126X_mcRun3_2022_realistic_postEE_v2-v2/GEN-SIM-RAW#e70265df-efb6-42ca-8858-1dcf669e68a2
```

and they belong to the following workflow: cmsunified_task_TRK-Run3Winter23wmLHEGS-00005__v1_T_230615_091700_9237

I see each of them has the maximum number of files defined in WMAgent, 500 files, and the error message we get back in the client is:
```
2023-08-03 12:35:58,964:140192869803840:INFO:DBSUploadPoller:About to call insert block for: /DYJetsToMuMu_M-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Winter23Digi-TRKRealistic_REAL_126X_mcRun3_2022_realistic_postEE_v2-v2/GEN-SIM-RAW#e70265df-efb6-42ca-8858-1dcf669e68a2
2023-08-03 12:35:59,690:140192869803840:ERROR:DBSUploadPoller:Error trying to process block /DYJetsToMuMu_M-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Winter23Reco-TRKRealistic_AlcaRecoRealisticTRK_REAL_126X_mcRun3_2022_realistic_postEE_v2-v2/GEN-SIM-RECO#c44686c3-86fa-4fc3-9902-ae328914b317 through DBS. Details: DBSError code: 110, message: 4cdac4592325e3196087c4671726e76b3a35851ab1fa81ed3b4121ef2323d989 unable to insert files, error DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.insertFilesViaChunks Message: Error: concurrency error, reason: DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.insertFilesViaChunks Message: Error: concurrency error
```

these blocks are inserted with the following dbsApi call:
```
            dbsApi.insertBulkBlock(blockDump=block)
```
as can be seen in this source code: https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py

I am also going to attach both block dumps (what WMAgent is posting to DBS Server) such that it makes debugging easier. Please find them here: https://amaltaro.web.cern.ch/amaltaro/forWMCore/dbs2go_98/

**Comment by amaltaro** [comment]
@d-ylee Hi Dennis, this is still a problem for central production and we have to keep a service running only because these 2 blocks are not going through. Would you be able to check the server logs and help me understanding why these blocks fail to get injected?

**Comment by d-ylee** [comment]
@amaltaro Are these from global prod?

**Comment by amaltaro** [comment]
@d-ylee yes, against cmsweb-prod cluster.

**Comment by d-ylee** [comment]
@amaltaro I checked the logs around that time. It shows that the concurrency error was happening in `insertFilesViaChunks`:
https://github.com/dmwm/dbs2go/blob/28e02bde209af797af7d59d4f7e3baba25a98605/dbs/bulkblocks2.go#L1002

For `/DYJetsToMuMu_M-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Winter23Reco-TRKRealistic_AlcaRecoRealisticTRK_REAL_126X_mcRun3_2022_realistic_postEE_v2-v2/GEN-SIM-RECO#c44686c3-86fa-4fc3-9902-ae328914b317`, I see that the `NErrors` in insertBulkBlocksConcurrently is **13**.

For `/DYJetsToMuMu_M-50_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Winter23Digi-TRKRealistic_REAL_126X_mcRun3_2022_realistic_postEE_v2-v2/GEN-SIM-RAW#e70265df-efb6-42ca-8858-1dcf669e68a2`, the `NErrors` is **7**.

`trec.NErrors` is only incremented in the `insertFilesChunk` function: https://github.com/dmwm/dbs2go/blob/28e02bde209af797af7d59d4f7e3baba25a98605/dbs/bulkblocks2.go#L1018

Within the function, there are three locations where `trec.NError` is incremented.
1. https://github.com/dmwm/dbs2go/blob/28e02bde209af797af7d59d4f7e3baba25a98605/dbs/bulkblocks2.go#L1028-L1034
2. https://github.com/dmwm/dbs2go/blob/28e02bde209af797af7d59d4f7e3baba25a98605/dbs/bulkblocks2.go#L1050-L1055
3. https://github.com/dmwm/dbs2go/blob/28e02bde209af797af7d59d4f7e3baba25a98605/dbs/bulkblocks2.go#L1078-L1085

For 2, I do not see `### wrong is _file_valid...` in the logs, so I don't think it is at 2.

It is hard to tell if it is 1 or 3 because in production, the configuration sets verbosity to 0. In this case, I do not see the messages printed corresponding to 1 or 3.

For the 3rd location, it could also be occurring in the `Files.Insert` function:
https://github.com/dmwm/dbs2go/blob/28e02bde209af797af7d59d4f7e3baba25a98605/dbs/files.go#L268

This could be happening when the sql statement is being executed: https://github.com/dmwm/dbs2go/blob/28e02bde209af797af7d59d4f7e3baba25a98605/dbs/files.go#L292-L314

Beyond this, it is hard to see why there was this error while looking at the production logs. @amaltaro Do you know the 13 and 7 files that could potentially have this issue?

Side note: I think we might need to have some of the messages be taken out of verbosity statements, especially for the `File.Insert` function. I cannot tell exactly which files failed to be inserted, causing the concurrency error.

**Comment by vkuznet** [comment]
From my previous experience with debugging these kind of errors they come from inconsistent JSON configuration where for file/block injection there should be proper configuration in place and in concurrent environment it is not there. I reported already that bulkblock DBS API is not concurrently safe by design, i.e. it has racing condition, see my report in this ticket: https://github.com/dmwm/WMCore/issues/11106

**Comment by jenimal** [comment]
This workflow is in rejected archived don't worry blow it away
